blank_issues_enabled: false
contact_links:
- name: Feedback
    url: https://github.com/Freibier-Protokoll/FreibierWallet/.github/ISSUE_TEMPLATE/CommunityIssue.md
    about: Vorlage zum Verfassen eines Feedback an die Entwickler
